theme: jekyll-theme-minimal
title: brain-smart.org
# description: A short description of your site's purpose 
logo: images/bsmartface.jpg
show_downloads: "true"
# github:
#  is_project_page: true
#  is_user_page: false
  
